BibliotecaWeb/Controllers/GeneroLiterarioController.cs
using BibliotecaData.Contrato;
using BibliotecaEntidades;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BibliotecaWeb.Controllers
{
    [Authorize]

    public class GeneroLiterarioController : Controller
    {
        private readonly IGeneroLiterarioRepositorio _repositorio;
        public GeneroLiterarioController(IGeneroLiterarioRepositorio repositorio)
        {
            _repositorio = repositorio;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            List<GeneroLiterario> lista = await _repositorio.Lista();
            return StatusCode(StatusCodes.Status200OK, new { data = lista });
        }

        [HttpGet]
        public async Task<IActionResult> Obtener(int IdGenero)
        {
            GeneroLiterario objeto = await _repositorio.Obtener(IdGenero);
            if (objeto != null)
                return StatusCode(StatusCodes.Status200OK, new { data = objeto });
            else
                return StatusCode(StatusCodes.Status404NotFound, new { data = objeto });
        }

        [HttpPost]
        public async Task<IActionResult> Guardar([FromBody] GeneroLiterario objeto)
        {
            string respuesta = await _repositorio.Guardar(objeto);
            return StatusCode(StatusCodes.Status200OK, new { data = respuesta });
        }


        [HttpPut]
        public async Task<IActionResult> Editar([FromBody] GeneroLiterario objeto)
        {
            string respuesta = await _repositorio.Editar(objeto);
            return StatusCode(StatusCodes.Status200OK, new { data = respuesta });
        }

        [HttpDelete]
        public async Task<IActionResult> Eliminar(int IdGenero)
        {
            int respuesta = await _repositorio.Eliminar(IdGenero);
            return StatusCode(StatusCodes.Status200OK, new { data = respuesta });
        }
    }
}


BibliotecaWeb/Views/Categoria/Index.cshtml
@section Estilos {
    <link href="~/lib/datatables2/css/datatables.datatables.css" rel="stylesheet" />
}
<h2 class="mt-4 mb-4">Categorias</h2>

<div class="row">
    <div class="col-sm-12">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-chart-bar me-1"></i>
                Lista de Categorias
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-3">
                        <button class="btn btn-outline-success" id="btnNuevaCategoria">Nueva Categoria</button>
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-sm-12">
                        <table class="display" id="tbCategoria" cellspacing="0" style="width:100%">
                        </table>
                    </div>
                </div>
               
            </div>
            
        </div>
    </div>
</div>

<div class="modal fade" id="mdCategoria" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Categoria</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">
                        <label class="col-form-label">Nombre:</label>
                        <input type="text" class="form-control" id="txtNombre" autocomplete="off">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" id="btnGuardar">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/datatables2/js/moment.min.js"></script>
    <script src="~/lib/datatables2/js/datatables.js"></script>
    <script src="~/views/categoria/categoria.js"></script>

}

BibliotecaWeb/Views/GeneroLiterario/Index.cshtml
@section Estilos {
    <link href="~/lib/datatables2/css/datatables.datatables.css" rel="stylesheet" />
}
<h2 class="mt-4 mb-4">Generos</h2>

<div class="row">
    <div class="col-sm-12">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-chart-bar me-1"></i>
                Lista de Generos
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-3">
                        <button class="btn btn-outline-success" id="btnNuevoGenero">Nuevo Genero</button>
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-sm-12">
                        <table class="display" id="tbGeneroLiterario" cellspacing="0" style="width:100%">
                        </table>
                    </div>
                </div>
               
            </div>
            
        </div>
    </div>
</div>

<div class="modal fade" id="md" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Genero</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">
                        <label class="col-form-label">Nombre:</label>
                        <input type="text" class="form-control" id="txtNombre" autocomplete="off">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" id="btnGuardar">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/datatables2/js/moment.min.js"></script>
    <script src="~/lib/datatables2/js/datatables.js"></script>
    <script src="~/views/generoliterario/generoliterario.js"></script>

}

BibliotecaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Tables - SB Admin</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    @RenderSection("Estilos", required: false)
    <script src="~/lib/fontawesome/all.js"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Biblioteca</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
           @*  <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div> *@
        </form>
        <!-- Navbar-->
        @await Component.InvokeAsync("MenuUsuario")
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Gestion</div>
                        <a class="nav-link" asp-controller="Usuario" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Usuarios
                        </a>
                        <a class="nav-link" asp-controller="Prestamo" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Prestamos
                        </a>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Libros
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="Libro" asp-action="Index">Lista Libros</a>
                                <a class="nav-link" asp-controller="Categoria" asp-action="Index">Categorias</a>
                                <a class="nav-link" asp-controller="GeneroLiterario" asp-action="Index">Genero</a>
                            </nav>
                        </div>
                       
                        <a class="nav-link" asp-controller="Estudiante" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Estudiantes
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/scripts.js"></script>
    <script src="~/lib/sweetalert2/js/sweetalert2.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>